#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Rexiel Scarlet"
email = "37258415+Rexcrazy804@users.noreply.github.com"

[signing]
# its far better to lazily sign on push lest you should 
# enter you password each time you git clone something
behavior = "drop"
backend = "gpg"
key = "00AC2D589EE7B0EBA5F03969E22FC5FD4007C746"

[git]
colocate = true
sign-on-push = true
write-change-id-header = true

[ui]
default-command = "diff"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-instructions = false

[aliases]
push = ["git", "push"]
pull-pr = { definition = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "set -euo pipefail; git fetch $0 pull/$1/head:$2",
], doc = "A convenient alias to pull a pr $1 from remote $0 into branch $2" }
patch = { definition = [
  "util",
  "exec",
  "git",
  "push",
  "rad",
  "HEAD:refs/patches",
], doc = "create a new radicle patch" }

[fix.tools.alejandra]
command = ["alejandra", "--quiet", "-"]
patterns = ["**/*.nix"]
enabled = true

[fix.tools.taplo]
command = ["taplo", "format", "-"]
patterns = ["**/*.toml"]
enabled = true

[templates]
git_push_bookmark = '"rexies/push-" ++ change_id.short()'
