require('plugins.options')
require('plugins.keybinds')
require('plugins.extraft')
require('plugins.themes')
require('plugins.generic')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.blink')
require('plugins.gitsigns')
require('plugins.dbee')
require('plugins.lsp')
-- require('plugins.cmp')
