# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.kernelParams = ["idle=nowwait" "iommu=pt"];
  boot.extraModulePackages = with config.boot.kernelPackages; [lenovo-legion-module];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6c64bac4-08fd-40e4-b995-5f164175dffb";
    fsType = "ext4";
    options = ["discard"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CA65-6D27";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/run/media/rexies/subzero" = {
    device = "/dev/disk/by-uuid/c97eafca-0e24-4969-99f9-7ee03516a90f";
    fsType = "btrfs";
    options = ["compress=zstd"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/d329feee-a8a6-48f4-afb2-3375adff50a3";}
  ];

  zramSwap.enable = true;
  zramSwap.memoryPercent = 20;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
