"$schema" = 'https://starship.rs/config-schema.json'
format = """
$username$hostname \
$git_branch$git_status$git_state \
$nix_shell
$directory[ ](fg:primary_bg bg:primary_fg bold) 
"""

add_newline = false

palette = 'colors'

[palettes.colors]
primary_bg = '#ffb4ab'
primary_fg = '#561e1a'
secondary_bg = '#e7bdb8'
secondary_fg = '#442926'
tertiary_bg = '#e0c38c'
tertiary_fg = '#3f2e04'

[directory]
format = "[ 󰉋 ](bg:primary_bg fg:primary_fg)[ $path ](fg:primary_bg bg:primary_fg)"

[git_branch]
format = "[  ](bg:tertiary_bg fg:tertiary_fg)[ $branch ](fg:tertiary_bg bg:tertiary_fg)"

[git_status]
ahead = '[  ](fg:tertiary_bg bg:tertiary_fg)'
behind = '[  ](fg:tertiary_bg bg:tertiary_fg)'
up_to_date = '[ 󰔓 ](fg:tertiary_bg bg:tertiary_fg)'
untracked = '[  $count ](fg:tertiary_bg bg:tertiary_fg)'
modified = '[  $count ](fg:tertiary_bg bg:tertiary_fg)'
staged = '[  $count ](fg:tertiary_bg bg:tertiary_fg)'
stashed = '[ 󰆓 $count ](fg:tertiary_bg bg:tertiary_fg)'
format = "$ahead_behind$modified$staged$untracked$stashed"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)](fg:tertiary_bg bg:tertiary_fg)'

[nix_shell]
disabled = false
impure_msg = "impure"
format = "[ nix ](bg:secondary_bg fg:secondary_fg)[ $state ](fg:secondary_bg bg:secondary_fg)"

[username]
format = "[ $user ](fg:secondary_fg bg:secondary_bg)"
show_always = true
aliases = { "rexies" = "Rexies" }

[hostname]
ssh_only = false
format = "[ @$hostname ](fg:secondary_bg bg:secondary_fg)"
