{colors}:
/*
qml
*/
''
  pragma Singleton
  import Quickshell
  Singleton {
  readonly property string background: "#aa${colors.background}"
  readonly property string error: "#${colors.error}"
  readonly property string error_container: "#${colors.error_container}"
  readonly property string inverse_on_surface: "#${colors.inverse_on_surface}"
  readonly property string inverse_primary: "#${colors.inverse_primary}"
  readonly property string inverse_surface: "#${colors.inverse_surface}"
  readonly property string on_background: "#${colors.on_background}"
  readonly property string on_error: "#${colors.on_error}"
  readonly property string on_error_container: "#${colors.on_error_container}"
  readonly property string on_primary: "#${colors.on_primary}"
  readonly property string on_primary_container: "#${colors.on_primary_container}"
  readonly property string on_primary_fixed: "#${colors.on_primary_fixed}"
  readonly property string on_primary_fixed_variant: "#${colors.on_primary_fixed_variant}"
  readonly property string on_secondary: "#${colors.on_secondary}"
  readonly property string on_secondary_container: "#${colors.on_secondary_container}"
  readonly property string on_secondary_fixed: "#${colors.on_secondary_fixed}"
  readonly property string on_secondary_fixed_variant: "#${colors.on_secondary_fixed_variant}"
  readonly property string on_surface: "#${colors.on_surface}"
  readonly property string on_surface_variant: "#${colors.on_surface_variant}"
  readonly property string on_tertiary: "#${colors.on_tertiary}"
  readonly property string on_tertiary_container: "#${colors.on_tertiary_container}"
  readonly property string on_tertiary_fixed: "#${colors.on_tertiary_fixed}"
  readonly property string on_tertiary_fixed_variant: "#${colors.on_tertiary_fixed_variant}"
  readonly property string outline: "#${colors.outline}"
  readonly property string outline_variant: "#${colors.outline_variant}"
  readonly property string primary: "#${colors.primary}"
  readonly property string primary_container: "#${colors.primary_container}"
  readonly property string primary_fixed: "#${colors.primary_fixed}"
  readonly property string primary_fixed_dim: "#${colors.primary_fixed_dim}"
  readonly property string scrim: "#${colors.scrim}"
  readonly property string secondary: "#${colors.secondary}"
  readonly property string secondary_container: "#${colors.secondary_container}"
  readonly property string secondary_fixed: "#${colors.secondary_fixed}"
  readonly property string secondary_fixed_dim: "#${colors.secondary_fixed_dim}"
  readonly property string shadow: "#${colors.shadow}"
  readonly property string surface: "#${colors.surface}"
  readonly property string surface_bright: "#${colors.surface_bright}"
  readonly property string surface_container: "#${colors.surface_container}"
  readonly property string surface_container_high: "#${colors.surface_container_high}"
  readonly property string surface_container_highest: "#${colors.surface_container_highest}"
  readonly property string surface_container_low: "#${colors.surface_container_low}"
  readonly property string surface_container_lowest: "#${colors.surface_container_lowest}"
  readonly property string surface_dim: "#${colors.surface_dim}"
  readonly property string surface_tint: "#${colors.surface_tint}"

  readonly property string surface_variant: "#${colors.surface_variant}"
  readonly property string tertiary: "#${colors.tertiary}"
  readonly property string tertiary_container: "#${colors.tertiary_container}"
  readonly property string tertiary_fixed: "#${colors.tertiary_fixed}"
  readonly property string tertiary_fixed_dim: "#${colors.tertiary_fixed_dim}"
  }
''
