# background
root_color=0x{{colors.background.default.hex_stripped}}ff
# on_primary
border_color=0x{{colors.on_primary.default.hex_stripped}}ff
# primary
focus_color=0x{{colors.primary.default.hex_stripped}}ff
# error
urgent_color=0x{{colors.error.default.hex_stripped}}ff
# tertiary
global_color=0x{{colors.tertiary.default.hex_stripped}}ff
# secondary
scratchpad_color=0x{{colors.secondary.default.hex_stripped}}ff
overlay_color=0x{{colors.secondary.default.hex_stripped}}ff
maximized_screen_color=0x{{colors.secondary.default.hex_stripped}}ff
