name: "Benchmark Aphrodite Eval"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.nix'
      - '!templates/**'
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: rexielscarlet
    # TODO get rid of redundancy
    - run: nix shell nixpkgs#nixos-rebuild-ng --command nixos-rebuild-ng build --flake .#Aphrodite
    - run: time nix eval .#nixosConfigurations.Aphrodite.config.system.build.toplevel --substituters "" --option eval-cache false --raw --read-only
    - run: time nix eval .#nixosConfigurations.Aphrodite.config.system.build.toplevel --substituters "" --option eval-cache false --raw --read-only
    - run: time nix eval .#nixosConfigurations.Aphrodite.config.system.build.toplevel --substituters "" --option eval-cache false --raw --read-only
    - run: time nix eval .#nixosConfigurations.Aphrodite.config.system.build.toplevel --substituters "" --option eval-cache false --raw --read-only
