name: "Format pull request"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  style-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: rexielscarlet
    - run: nix fmt chk FILES_ALL=1
